version: "3"
volumes:
  pip:
services:
  # localhost:8123
  hass:
    image: homeassistant/home-assistant:2024.1.0
    restart: unless-stopped
    volumes:
      - ./hass:/config
      - ./custom_components:/config/custom_components:ro
    environment:
      TZ: Europe/Stockholm
    ports: [ "8123:8123" ]
  lint:
    image: cimg/python:3.11
    volumes:
      - "./:/files:ro"
      - pip:/tmp/pip:ro
    working_dir: /files
    entrypoint: [ pylint ]
    command:
      - custom_components/purei9
      - tests
  pip_install:
    image: cimg/python:3.11
    volumes:
      - "./requirements.txt:/requirements.txt:ro"
      - pip:/home/circleci/pip
    entrypoint: [ pip3 ]
    command:
      - install
      - --target
      - ~/pip
      - --no-cache-dir
      - --requirement
      - /requirements.txt
      - --upgrade
  test:
    image: cimg/python:3.11
    volumes:
      - "./:/files:ro"
      - pip:/tmp/pip:ro
    working_dir: /files
    entrypoint: [ python3 ]
    command:
      - -m
      - unittest
      - discover
      - --start-directory
      - tests
      - --verbose
