version: "3"
services:
  # localhost:8123
  hass:
    image: homeassistant/home-assistant:2024.1.1
    restart: unless-stopped
    volumes:
      - ./hass:/config
      - ./custom_components:/config/custom_components:ro
    environment:
      TZ: Europe/Stockholm
    ports: [ "8123:8123" ]
