version: "3"
services:
  purei9:
    build:
      context: .
    volumes: [ "./:/home/purei9/files:ro" ]
    tty: true
    stdin_open: true
    read_only: true
    tmpfs:
      - /tmp
      - /home/purei9/.cache
      - /home/purei9/.local
