version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/python:3.9
    steps:
      - run: sudo apt-get update && sudo apt-get install -y pylint
      - checkout
      - run: pip install -r requirements.txt
      - run: pylint custom_components/purei9
workflows:
  purei9:
    jobs:
      - lint
