version: 2.1
jobs:
  purei9:
    docker:
      - image: cimg/python:3.9
    steps:
      - run: apt-get update && apt-get install -y pylint
      - run: pip install
      - run: find custom_components/purei9 -name "*.py" -exec pylint {} \;
workflows:
  purei9:
    jobs:
      - purei9
