version: 2.1
commands:
  pip:
    steps:
      - restore_cache:
          key: '{{ checksum "requirements.txt" }}'
      - run: >-
          pip install
          --no-cache-dir
          --disable-pip-version-check
          --no-clean
          --cache-dir /tmp/pip
          --requirement requirements.txt
      - save_cache:
          key: '{{ checksum "requirements.txt" }}'
          paths: [ /tmp/pip ]
jobs:
  lint:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - pip
      - run: pylint custom_components/purei9
workflows:
  purei9:
    jobs:
      - lint
